#ifndef ARP_SHADOW
#define ARP_SHADOW


#define MAX_DIRECTIONAL_SHADOW_LIGHTS 4
#define MAX_CASCADE 4

CBUFFER_START(Shadow)

float4x4 _DirWorldToShadowMatrix[MAX_DIRECTIONAL_SHADOW_LIGHTS * MAX_CASCADE];
float4 _CullingSphere[MAX_DIRECTIONAL_SHADOW_LIGHTS];

CBUFFER_END

TEXTURE2D_SHADOW(_DIRECTIONAL_SHADOWMAP);
SAMPLER_CMP(sampler_DIRECTIONAL_SHADOWMAP);








#endif